### PR TITLE
Fixed UTF-8 encoding for message

### LINKED ISSUE #1: UTF-8 encoding is not handled correctly
I had tried to send message with "data" field that contains some fields with Russian letters, and when I have received this message on Android, Russian letters wasn't handled correctly.

### PR DESCRIPTION
**Pull request by ntngel1**

### CODE REVIEW

File: src/main/kotlin/mrblrrd/fcmsend/FcmSend.kt [hunk 1]
```diff
@@ -67,7 +68,7 @@ private class FcmSend : CliktCommand(
             ).apply { doOutput = true }
 
         DataOutputStream(connection.outputStream).use { outputStream ->
-            outputStream.writeBytes(message)
+            outputStream.write(message.encodeToByteArray())
```
Comment (mrblrrd) [inline src/main/kotlin/mrblrrd/fcmsend/FcmSend.kt]: Thank you! I have the only question.

```suggestion
            outputStream.write(message.toByteArray(Charsets.UTF_8))
```
What's the reason for using experimental API instead of `toByteArray` which is used under the hood? Is this for multiplatform?

Comment (ntngel1) [reply src/main/kotlin/mrblrrd/fcmsend/FcmSend.kt]: Yeah, you're right, my mistake

Comment (mrblrrd) [reply src/main/kotlin/mrblrrd/fcmsend/FcmSend.kt]: Not really a mistake. It’s a good idea to make this project MPP... 🤔 Thanks.

**Review by mrblrrd — APPROVED** [review]
